import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [pokemons, setPokemons] = useState([]);

  const getPokemons = () => {
    const pokemonsPromise = Array(100)
      .fill()
      .map((_, index) =>
        fetch(`https://pokeapi.co/api/v2/pokemon/${index + 1}`).then((res) =>
          res.json()
        )
      );

    Promise.all(pokemonsPromise).then((pokemons) => {
      const formattedPokemons = pokemons.map(({ name, id, types, sprites }) => {
        const elementTypes = types.map((type) => type.type.name);

        return {
          name,
          id,
          image: sprites.front_default,
          elementTypes,
        };
      });

      setPokemons(formattedPokemons);
    });
  };

  useEffect(() => {
    getPokemons();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Pokédex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <h1 className={styles.title}>Pokédex</h1>
        <div className={styles.pokedex}>
          {pokemons.map(({ name, id, image, elementTypes }) => (
            <a
              href={`pokemon/${name}`}
              key={id}
              className={`${styles.card} ${styles[elementTypes[0]]}`}
            >
              <Image
                className={styles["card-image"]}
                alt={name}
                src={image}
                width={150}
                height={150}
              />
              <h2 className={styles["card-title"]}>
                {id}. {name}
              </h2>
              <p className={styles["card-subtitle"]}>
                {elementTypes.join(" | ")}
              </p>
            </a>
          ))}
        </div>
      </div>
    </div>
  );
}
